name: PlugDj
main: PlugDj
description: Requested Plugin by undeaD_D
version: 4.0
author: DieFriiks
authors: [DieFriiks, CustomCraftDev, undeaD_D]
commands:
  plugdj:
    usage: /plugdj <reload/reset>
    description: Commands from PlugDj plugin
